# Generated by Django 4.2.1 on 2024-03-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-time_create'], name='recipes_rec_time_cr_b29e3c_idx'),
        ),
    ]

